title: "Porsche 944 MicroSquirt Conversion"
description: "Documentation for converting NA Porsche 944 to MicroSquirt ECU"
theme: minima

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Show excerpts on homepage
show_excerpts: true

# Disable automatic navigation generation
header_pages: []

# Disable minima's automatic page listing
minima:
  date_format: "%b %-d, %Y"
  
# Override repository name display
github_username: ""
repository: ""