title: "Porsche 944 MicroSquirt Conversion"
description: "Documentation for converting NA Porsche 944 to MicroSquirt ECU"
theme: minima

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Show excerpts on homepage
show_excerpts: true